"""
Member 4 - Alert Manager

Creates and stores security alerts generated by the
autonomous response engine.
"""

alerts = []


def create_alert(verdict, action_result):
    """Create a security alert from a detection verdict."""

    alert = {
        "ip": verdict.get("ip"),
        "attack_type": verdict.get("attack_type"),
        "risk_score": verdict.get("risk_score"),
        "severity": action_result.get("severity"),
        "action": action_result.get("action"),
        "confidence": verdict.get("confidence"),
        "risk_level": verdict.get("risk_level"),
    }

    alerts.append(alert)
    return alert


def get_alerts():
    """Return all generated security alerts."""
    return alerts.copy()


def clear_alerts():
    """Clear all stored alerts."""
    alerts.clear()